### PR TITLE
feat(graph): add graph functionality

### PR DESCRIPTION
**Pull request by ruru-m07**

### CODE REVIEW

**Comment by Lohit-pro** [comment]
@ruru-m07 please share screenshots if any/after your work is done.

**Comment by ruru-m07** [comment]
> @ruru-m07 please share screenshots if any/after your work is done.

sure for now this PR is still draft. :D

**Comment by Akshaygore1** [comment]
> @ruru-m07 please share screenshots if any/after your work is done.

I only told him to do the changes

**Comment by ruru-m07** [comment]
## the UI untill this commit. https://github.com/Akshaygore1/FakeStake/pull/7/commits/338fee09ac7ed900be0756552b77fdf8af39304b
image

**Comment by Akshaygore1** [comment]
can we do something like this

image
I will tell the logic actully graph will grow on basis of the time in X axis time is there and Y axis multiplier is there

**Comment by Lohit-pro** [comment]
I'm actually ready to help on this. Feel free to tag me if required.

**Pull request closed without merging**
