### PR TITLE
UI enhancements

### PR DESCRIPTION
**Pull request by Lohit-pro**

### CODE REVIEW

**Comment by Akshaygore1** [comment]
@Lohit-pro there us font called breathe can you explore that so instead of using the png we can put text
Black And White Modern Brush Font Logo

**Comment by Akshaygore1** [comment]
> @Lohit-pro there us font called breathe can you explore that so instead of using the png we can put text Black And White Modern Brush Font Logo

This is Looking Better

**Comment by Lohit-pro** [comment]
@Akshaygore1 ??👀

**Comment by Akshaygore1** [comment]
image
other than this every thing is perfect can you revert this other ui is so good

**Comment by Lohit-pro** [comment]
> image other than this every thing is perfect can you revert this other ui is so good

you mean I should revert the changes back to normal? 
"Welcome to fake stake" one?

**Comment by Akshaygore1** [comment]
> > image other than this every thing is perfect can you revert this other ui is so good
> 
> you mean I should revert the changes back to normal? "Welcome to fake stake" one?

yes

**Pull request closed without merging**
